name: Deploy to IONOS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to IONOS server
      uses: appleboy/scp-action@master
      with:
        host: access951720039.webspace-data.io
        username: u111236921
        password: suckmyballstrump
        port: 22
        source: "./"
        target: "./"