name: Deploy to Ionos.com

on:
  push:
    branches:
      - main # Update this with the name of the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SFTP action
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: access951720039.webspace-data.io
        username: u111236921
        password: suckmyballstrump
        local-dir: ./ # Set this to the directory that contains your website files
        server-dir: ./ # Set this to the directory on the Ionos.com server where you want to deploy the file(s)
